name: rollcallapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 22.11.1+23

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  location: ^4.4.0
  http: ^0.13.5
  dio: ^5.4.1
  connectivity: ^3.0.6
  url_launcher: ^6.1.6
  map_launcher: ^2.4.0
  platform_device_id: ^1.0.1
  launch_review: ^3.0.1
  image_picker: ^0.8.6
  shared_preferences: 
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.11
  av_smooth_star_rating: ^1.1.2
  camera: ^0.10.0+4
  flutter_barcode_scanner: ^2.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.2.1
  intl: ^0.17.0
  geocoding: ^2.0.4
  geolocator: ^11.0.0
  store_redirect: ^2.0.1
  localstorage: ^4.0.1+4
  
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/rc_logo.png
    - images/drawerbackground.jpg
    - images/backgroundimage.png
    - images/profile.png
    - images/background.png
    - images/perennialcode.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
